# 端口号
server:
  port: 8004

# 日志格式
logging:
  pattern:
   console: '%d{HH:mm:ss.SSS} %clr(%-5level) ---  [%-15thread] %cyan(%-50logger{50}):%msg%n'

# Nacos
spring:
  application:
   name: shopping_search_customer_api
  cloud:
   nacos:
    discovery:
     server-addr: 192.168.66.100:8848

dubbo:
  application:
  #项目名字
   name: shopping_search_customer_api
  protocol:
   name: dubbo
   port: -1
  registry:
  # 注册地址
   address: nacos://192.168.66.100:8848